### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jcobol** [gegy1000/Terrarium#2] opened 2017-09-12 01:28 UTC
I tried building on Fedora 22 and the latest Ubuntu and get the same error each time:

$ ./gradlew clean build
...
Applying SpecialSource...
:deobfMcMCP FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deobfMcMCP'.
> java.util.zip.ZipException: duplicate entry: net/minecraft/command/AdvancementCommand$Mode.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by shweshiki** [comment] 2017-12-09 18:01
Same

**Comment by Gegy** [comment] 2017-12-09 19:33
This is certainly weird -- but I don't see how it could be related to my buildscript. I can't reproduce this on Windows.

**Comment by shweshiki** [comment] 2017-12-14 03:42
Tried it on windows and debian and got the same thing. Can you upload a compiled version somewhere?

**Comment by shweshiki** [comment] 2017-12-14 03:45
Determining if task ':deobfMcMCP' is up-to-date                                                                                                         19:29:42.479 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':deobfMcMCP' (up-to-date check took 0.016 secs) due to:                                                                                    No history is available.                                                                                              19:29:42.494 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':deobfMcMCP'.                                                                                                             19:29:42.510 [LIFECYCLE] [org.gradle.api.Task] Applying SpecialSource...                                                19:29:42.869 [INFO] [org.gradle.api.Task] Using AccessTransformers...                                                   19:29:42.885 [INFO] [org.gradle.api.Task] C:\Users\shwes\.gradle\caches\minecraft\net\minecraftforge\forge\1.12-14.21.0.2331\userdev\merged_at.cfg                                                                                              19:30:15.541 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':deobfMcMCP'                                                                                                              19:30:15.557 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :deobfMcMCP FAILED   

this is the output I get on windows 10 with gradlew build --debug

**Comment by Gegy** [comment] 2018-01-01 06:59
I've recently made a lot of changes. Does this still occur?

**Comment by shweshiki** [comment] 2018-01-03 08:11
is goooooooooooooooooooood!

**Comment by shweshiki** [comment] 2018-01-03 08:12
(it's fixed now)

**Closed as completed** 2018-01-03 08:31 UTC
