### ISSUE TITLE
CubicChunks integration?

### ISSUE THREAD

**Issue by juh9870** [gegy1000/Terrarium#45] opened 2018-07-11 10:23 UTC
It will be great if this mod will be compatable with Open Cubic Chunks, it changes world height bounds to HUGE values https://github.com/OpenCubicChunks/CubicChunks
I'd like to explore mountains and plains and in 1:1 scale

**Comment by cam72cam** [comment] 2018-07-11 12:04
This is a duplicate of https://github.com/gegy1000/Terrarium/issues/11, please close this issue

**Closed as completed** 2018-07-11 12:25 UTC
Labels: duplicate
